version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - ${PORT}:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=1
  redis:
    image: redis
